SCRIPT_NAMES = ['агата', 'арго', 'эталина',
                'фиорита', 'гинда', 'жанели',
                'джети', 'куртки', 'лкрафт',
                'сумкистиль', 'боссанова',
                "синий лен", 'клевер-\nмедиа', 'раш']

COMMON_STYLE = ("QPushButton{position: absolute;\n"
                "width: 168px;\n"
                "height: 168px;\n"
                "left: calc(50% - 168px/2 - 435px);\n"
                "top: 75px;\n"
                "\n"
                "background: #C3FD1F;\n"
                "border-radius: 15px;\n"
                "\n"
                "font-family: \'Inter\';\n"
                "font-style: normal;\n"
                "font-weight: 400;\n"
                "font-size: 20px;\n"
                "line-height: 24px;\n"
                "display: flex;\n"
                "align-items: center;}\n"
                "QPushButton:hover{position: absolute;\n"
                "width: 168px;\n"
                "height: 168px;\n"
                "left: calc(50% - 168px/2 + 217px);\n"
                "top: 75px;\n"
                "\n"
                "background: #A7D030;\n"
                "border-radius: 15px;\n"
                "font-family: \'Inter\';\n"
                "font-style: normal;\n"
                "font-weight: 400;\n"
                "font-size: 20px;\n"
                "line-height: 24px;\n"
                "display: flex;}\n"
                "QPushButton:pressed\n"
                "{position: absolute;\n"
                "width: 168px;\n"
                "height: 168px;\n"
                "left: calc(50% - 168px/2 + 217px);\n"
                "top: 75px;\n"
                "\n"
                "background: #A7D030;\n"
                "border: 3px solid #373E43;\n"
                "border-radius: 15px;\n"
                "font-family: \'Inter\';\n"
                "font-style: normal;\n"
                "font-weight: 400;\n"
                "font-size: 20px;\n"
                "line-height: 24px;\n"
                "display: flex;}"
                # "QPushButton:checked{position: absolute;\n"
                #  "width: 168px;\n"
                #  "height: 168px;\n"
                #  "left: calc(50% - 168px/2 - 435px);\n"
                #  "top: 75px;\n"
                #  "\n"
                #  "background: #EAC713;\n"
                #  "border-radius: 15px;\n"
                #  "\n"
                #  "font-family: \'Inter\';\n"
                #  "font-style: normal;\n"
                #  "font-weight: 400;\n"
                #  "font-size: 20px;\n"
                #  "line-height: 24px;\n"
                #  "display: flex;\n"
                #  "align-items: center;}"
                )

LOADING_STYLE = ("QPushButton{position: absolute;\n"
                 "width: 168px;\n"
                 "height: 168px;\n"
                 "left: calc(50% - 168px/2 - 435px);\n"
                 "top: 75px;\n"
                 "\n"
                 "background: #EAC713;\n"
                 "border-radius: 15px;\n"
                 "\n"
                 "font-family: \'Inter\';\n"
                 "font-style: normal;\n"
                 "font-weight: 400;\n"
                 "font-size: 20px;\n"
                 "line-height: 24px;\n"
                 "display: flex;\n"
                 "align-items: center;}\n"
                 "QPushButton:hover{position: absolute;\n"
                 "width: 168px;\n"
                 "height: 168px;\n"
                 "left: calc(50% - 168px/2 + 217px);\n"
                 "top: 75px;\n"
                 "\n"
                 "background: #D8B70D;\n"
                 "border-radius: 15px;\n"
                 "font-family: \'Inter\';\n"
                 "font-style: normal;\n"
                 "font-weight: 400;\n"
                 "font-size: 20px;\n"
                 "line-height: 24px;\n"
                 "display: flex;}\n"
                 "QPushButton:pressed\n"
                 "{position: absolute;\n"
                 "width: 168px;\n"
                 "height: 168px;\n"
                 "left: calc(50% - 168px/2 + 217px);\n"
                 "top: 75px;\n"
                 "\n"
                 "background: #D8B70D;\n"
                 "border: 3px solid #373E43;\n"
                 "border-radius: 15px;\n"
                 "font-family: \'Inter\';\n"
                 "font-style: normal;\n"
                 "font-weight: 400;\n"
                 "font-size: 20px;\n"
                 "line-height: 24px;\n"
                 "display: flex;}")

ERROR_STYLE = ''
