# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scripts.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 720)
        Form.setStyleSheet("background: #373E43")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setStyleSheet("QPushButton{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 - 435px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #C3FD1F;\n"
                                         "border-radius: 15px;\n"
                                         "\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;\n"
                                         "align-items: center;}\n"
                                         "QPushButton:hover{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #A7D030;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}\n"
                                         "QPushButton:pressed\n"
                                         "{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #A7D030;\n"
                                         "border: 3px solid #373E43;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setStyleSheet("QPushButton{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 - 435px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #C3FD1F;\n"
                                         "border-radius: 15px;\n"
                                         "\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;\n"
                                         "align-items: center;}\n"
                                         "QPushButton:hover{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #A7D030;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}\n"
                                         "QPushButton:pressed\n"
                                         "{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #A7D030;\n"
                                         "border: 3px solid #373E43;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_3.addWidget(self.pushButton_12)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setStyleSheet("QPushButton{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 - 435px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #C3FD1F;\n"
                                         "border-radius: 15px;\n"
                                         "\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;\n"
                                         "align-items: center;}\n"
                                         "QPushButton:hover{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #A7D030;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}\n"
                                         "QPushButton:pressed\n"
                                         "{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #A7D030;\n"
                                         "border: 3px solid #373E43;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_3.addWidget(self.pushButton_13)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setStyleSheet("QPushButton{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 - 435px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #C3FD1F;\n"
                                         "border-radius: 15px;\n"
                                         "\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;\n"
                                         "align-items: center;}\n"
                                         "QPushButton:hover{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #A7D030;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}\n"
                                         "QPushButton:pressed\n"
                                         "{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #A7D030;\n"
                                         "border: 3px solid #373E43;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_3.addWidget(self.pushButton_14)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setStyleSheet("QPushButton{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 - 435px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #1F92FD;\n"
                                         "border-radius: 15px;\n"
                                         "\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;\n"
                                         "align-items: center;}\n"
                                         "QPushButton:hover{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #0766BD;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}\n"
                                         "QPushButton:pressed\n"
                                         "{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #0766BDf;\n"
                                         "border: 3px solid #373E43;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_3.addWidget(self.pushButton_15)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("QPushButton{position: absolute;\n"
                                      "width: 168px;\n"
                                      "height: 168px;\n"
                                      "left: calc(50% - 168px/2 - 435px);\n"
                                      "top: 75px;\n"
                                      "\n"
                                      "background: #C3FD1F;\n"
                                      "border-radius: 15px;\n"
                                      "\n"
                                      "font-family: \'Inter\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 400;\n"
                                      "font-size: 20px;\n"
                                      "line-height: 24px;\n"
                                      "display: flex;\n"
                                      "align-items: center;}\n"
                                      "QPushButton:hover{position: absolute;\n"
                                      "width: 168px;\n"
                                      "height: 168px;\n"
                                      "left: calc(50% - 168px/2 + 217px);\n"
                                      "top: 75px;\n"
                                      "\n"
                                      "background: #A7D030;\n"
                                      "border-radius: 15px;\n"
                                      "font-family: \'Inter\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 400;\n"
                                      "font-size: 20px;\n"
                                      "line-height: 24px;\n"
                                      "display: flex;}\n"
                                      "QPushButton:pressed\n"
                                      "{position: absolute;\n"
                                      "width: 168px;\n"
                                      "height: 168px;\n"
                                      "left: calc(50% - 168px/2 + 217px);\n"
                                      "top: 75px;\n"
                                      "\n"
                                      "background: #A7D030;\n"
                                      "border: 3px solid #373E43;\n"
                                      "border-radius: 15px;\n"
                                      "font-family: \'Inter\';\n"
                                      "font-style: normal;\n"
                                      "font-weight: 400;\n"
                                      "font-size: 20px;\n"
                                      "line-height: 24px;\n"
                                      "display: flex;}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("QPushButton{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 - 435px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #C3FD1F;\n"
                                        "border-radius: 15px;\n"
                                        "\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;\n"
                                        "align-items: center;}\n"
                                        "QPushButton:hover{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}\n"
                                        "QPushButton:pressed\n"
                                        "{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border: 3px solid #373E43;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setStyleSheet("QPushButton{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 - 435px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #C3FD1F;\n"
                                        "border-radius: 15px;\n"
                                        "\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;\n"
                                        "align-items: center;}\n"
                                        "QPushButton:hover{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}\n"
                                        "QPushButton:pressed\n"
                                        "{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border: 3px solid #373E43;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("QPushButton{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 - 435px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #C3FD1F;\n"
                                        "border-radius: 15px;\n"
                                        "\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;\n"
                                        "align-items: center;}\n"
                                        "QPushButton:hover{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}\n"
                                        "QPushButton:pressed\n"
                                        "{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border: 3px solid #373E43;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("QPushButton{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 - 435px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #C3FD1F;\n"
                                        "border-radius: 15px;\n"
                                        "\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;\n"
                                        "align-items: center;}\n"
                                        "QPushButton:hover{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}\n"
                                        "QPushButton:pressed\n"
                                        "{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border: 3px solid #373E43;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem14, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setStyleSheet("QPushButton{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 - 435px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #C3FD1F;\n"
                                        "border-radius: 15px;\n"
                                        "\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;\n"
                                        "align-items: center;}\n"
                                        "QPushButton:hover{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}\n"
                                        "QPushButton:pressed\n"
                                        "{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border: 3px solid #373E43;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem16)
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("QPushButton{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 - 435px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #C3FD1F;\n"
                                        "border-radius: 15px;\n"
                                        "\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;\n"
                                        "align-items: center;}\n"
                                        "QPushButton:hover{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}\n"
                                        "QPushButton:pressed\n"
                                        "{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border: 3px solid #373E43;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem17)
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet("QPushButton{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 - 435px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #C3FD1F;\n"
                                        "border-radius: 15px;\n"
                                        "\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;\n"
                                        "align-items: center;}\n"
                                        "QPushButton:hover{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}\n"
                                        "QPushButton:pressed\n"
                                        "{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border: 3px solid #373E43;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem18)
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("QPushButton{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 - 435px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #C3FD1F;\n"
                                        "border-radius: 15px;\n"
                                        "\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;\n"
                                        "align-items: center;}\n"
                                        "QPushButton:hover{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}\n"
                                        "QPushButton:pressed\n"
                                        "{position: absolute;\n"
                                        "width: 168px;\n"
                                        "height: 168px;\n"
                                        "left: calc(50% - 168px/2 + 217px);\n"
                                        "top: 75px;\n"
                                        "\n"
                                        "background: #A7D030;\n"
                                        "border: 3px solid #373E43;\n"
                                        "border-radius: 15px;\n"
                                        "font-family: \'Inter\';\n"
                                        "font-style: normal;\n"
                                        "font-weight: 400;\n"
                                        "font-size: 20px;\n"
                                        "line-height: 24px;\n"
                                        "display: flex;}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem19)
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 - 435px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #C3FD1F;\n"
                                         "border-radius: 15px;\n"
                                         "\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;\n"
                                         "align-items: center;}\n"
                                         "QPushButton:hover{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #A7D030;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}\n"
                                         "QPushButton:pressed\n"
                                         "{position: absolute;\n"
                                         "width: 168px;\n"
                                         "height: 168px;\n"
                                         "left: calc(50% - 168px/2 + 217px);\n"
                                         "top: 75px;\n"
                                         "\n"
                                         "background: #A7D030;\n"
                                         "border: 3px solid #373E43;\n"
                                         "border-radius: 15px;\n"
                                         "font-family: \'Inter\';\n"
                                         "font-style: normal;\n"
                                         "font-weight: 400;\n"
                                         "font-size: 20px;\n"
                                         "line-height: 24px;\n"
                                         "display: flex;}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem20)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem21, 6, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_11.setText(_translate("Form", "ТРИКА"))
        self.pushButton_12.setText(_translate("Form", "ТРИКА"))
        self.pushButton_13.setText(_translate("Form", "ТРИКА"))
        self.pushButton_14.setText(_translate("Form", "ТРИКА"))
        self.pushButton_15.setText(_translate("Form", "ТРИКА"))
        self.pushButton.setText(_translate("Form", "ТРИКА"))
        self.pushButton_2.setText(_translate("Form", "ТРИКА"))
        self.pushButton_3.setText(_translate("Form", "ТРИКА"))
        self.pushButton_4.setText(_translate("Form", "ТРИКА"))
        self.pushButton_5.setText(_translate("Form", "ТРИКА"))
        self.pushButton_6.setText(_translate("Form", "ТРИКА"))
        self.pushButton_7.setText(_translate("Form", "ТРИКА"))
        self.pushButton_8.setText(_translate("Form", "ТРИКА"))
        self.pushButton_9.setText(_translate("Form", "ТРИКА"))
        self.pushButton_10.setText(_translate("Form", "ТРИКА"))
